use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// MCP server transport type, mirrors the original TypeScript ServerConfig
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, sqlx::Type)]
#[serde(rename_all = "kebab-case")]
#[sqlx(type_name = "TEXT", rename_all = "kebab-case")]
pub enum ServerType {
    Stdio,
    Sse,
    #[serde(rename = "streamable-http")]
    StreamableHttp,
    Openapi,
}

impl Default for ServerType {
    fn default() -> Self {
        Self::Stdio
    }
}

/// Options for MCP server connection behavior
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct ServerOptions {
    pub timeout: Option<u64>,
    pub reset_timeout_on_progress: Option<bool>,
    pub max_total_timeout: Option<u64>,
}

/// Full server configuration stored in DB / returned to frontend
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ServerConfig {
    // id is auto-generated by the DB; clients don't send it, so default to empty string
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub id: String,
    pub name: String,
    // The frontend uses the key "type" (not "serverType"), so we rename the field here.
    // default = ServerType::Stdio so configs that omit "type" are accepted gracefully.
    #[serde(rename = "type", default)]
    pub server_type: ServerType,
    pub description: Option<String>,
    // stdio fields
    pub command: Option<String>,
    pub args: Option<Vec<String>>,
    pub env: Option<HashMap<String, String>>,
    // http fields
    pub url: Option<String>,
    pub headers: Option<HashMap<String, String>>,
    // connection options
    pub options: Option<ServerOptions>,
    #[serde(default = "default_true")]
    pub enabled: bool,
}

fn default_true() -> bool { true }

/// Runtime status of a connected MCP server
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ServerStatus {
    pub name: String,
    pub connected: bool,
    pub tool_count: usize,
    pub error: Option<String>,
    pub last_connected: Option<String>,
}

/// A single MCP tool exposed by a server
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Tool {
    pub name: String,
    pub description: Option<String>,
    pub input_schema: serde_json::Value,
    pub server_name: String,
}

/// Result of a tool invocation
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ToolCallResult {
    pub content: Vec<serde_json::Value>,
    pub is_error: bool,
}

/// Combined server info returned to the dashboard
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ServerInfo {
    pub config: ServerConfig,
    pub status: ServerStatus,
    pub tools: Vec<Tool>,
}
